# Generated by Django 3.1.6 on 2021-02-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210204_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
